# AUTOGENERATED! DO NOT EDIT! File to edit: ../../Notebooks/01_SelfSupervised/01_00_jigsaw_puzzle.ipynb.

# %% auto 0
__all__ = []

# %% ../../Notebooks/01_SelfSupervised/01_00_jigsaw_puzzle.ipynb 3
from itertools import permutations

import numpy as np
from einops import rearrange
import tensorflow as tf
